version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: debtspassword
      POSTGRES_DB: debts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#  rabbitmq:
#    image: rabbitmq:management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
    driver: local
  solr_data:
  rabbitmq_data: