basePath: /
definitions:
  model.UserRequest:
    properties:
      email:
        type: string
      last_name:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Testing Swagger APIs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: debs API
  version: "1.0"
paths:
  /ping:
    get:
      description: ping operation
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping verify if app is running
      tags:
      - ping
  /v1/users:
    post:
      consumes:
      - application/json
      description: Add a new User
      parameters:
      - description: User Request Body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User Created
          schema:
            $ref: '#/definitions/model.UserRequest'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Register User
      tags:
      - user
schemes:
- http
swagger: "2.0"
